name: Pokedex
options:
    bundleIdPrefix: Filipero.pokedex
    deploymentTarget: "13.7"
    createIntermediateGroups: true

targetTemplates:
    Default:


targets:
    "pokedex":
        templates: Default
        type: application
        platform: iOS
        sources: ["pokedex"]
        dependencies: [package: NetworkManager]
        info:
            path: "pokedex/Info.plist"
            properties:
                CFBundleVersion: "1"
                UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
                UILaunchStoryboardName: LaunchScreen

packages:
    NetworkManager:
        url: git@github.com:filipero/NetworkManager.git
        branch: master

