name: Pokedex
options:
    bundleIdPrefix: Filipero.Pokedex
    deploymentTarget: "13.7"
    createIntermediateGroups: true

targetTemplates:
    Default:


targets:
    Pokedex:
        templates: Default
        type: application
        platform: iOS
        sources:
            - path: Pokedex
        dependencies:
            - package: NetworkManager
            - package: TinyConstraints
        scheme:
            testTargets:
            - PokedexTests
        info:
            path: Pokedex/Info.plist
            properties:
                CFBundleVersion: "1"
                UILaunchStoryboardName: LaunchScreen
    PokedexTests:
        type: "bundle.unit-test"
        platform: iOS
        sources:
            - path: PokedexTests
        dependencies:
         - target: Pokedex
         - package: SnapshotTesting
        info:
            path: PokedexTests/Info.plist

packages:
    NetworkManager:
        url: https://github.com/filipero/NetworkManager.git
        branch: master
    TinyConstraints:
        url: https://github.com/roberthein/TinyConstraints.git
        branch: master
    SnapshotTesting:
        url: https://github.com/pointfreeco/swift-snapshot-testing
        exactVersion: 1.14.2
